-- CreateTable
CREATE TABLE `notifications` (
    `id` VARCHAR(191) NOT NULL,
    `type` ENUM('ACCOUNT_CREATED', 'ACCOUNT_APPROVED', 'ACCOUNT_REJECTED', 'PROFILE_UPDATED', 'PASSWORD_CHANGED', 'RESERVATION_REQUESTED', 'RESERVATION_APPROVED', 'RESERVATION_DECLINED', 'RESERVATION_CANCELLED', 'RESERVATION_REMINDER', 'PAYMENT_RECEIVED', 'PAYMENT_OVERDUE', 'PAYMENT_FAILED', 'PAYMENT_REFUNDED', 'MONTHLY_SUBSCRIPTION_PAYMENT', 'SYSTEM_MAINTENANCE', 'SYSTEM_UPDATE', 'NEW_FEATURE', 'ANNOUNCEMENT', 'CLUB_REGISTRATION_SUBMITTED', 'CLUB_REGISTRATION_APPROVED', 'CLUB_REGISTRATION_REJECTED', 'EMAIL_SENT', 'EMAIL_VERIFIED', 'WELCOME_EMAIL', 'NEW_USER_REGISTERED', 'NEW_RESERVATION_REQUEST', 'PAYMENT_REQUIRES_ATTENTION') NOT NULL,
    `title` VARCHAR(191) NOT NULL,
    `message` VARCHAR(191) NOT NULL,
    `isRead` BOOLEAN NOT NULL DEFAULT false,
    `userId` VARCHAR(191) NOT NULL,
    `metadata` JSON NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `notifications_userId_idx`(`userId`),
    INDEX `notifications_isRead_idx`(`isRead`),
    INDEX `notifications_type_idx`(`type`),
    INDEX `notifications_createdAt_idx`(`createdAt`),
    INDEX `notifications_userId_isRead_idx`(`userId`, `isRead`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `notifications` ADD CONSTRAINT `notifications_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
