// ⚠️ AUTO-GENERATED — DO NOT EDIT
// Generated by scripts/generate-i18n.ts

/* ---------------- Translation keys ---------------- */
export type TranslationKey =
    | 'common.actions.add_to_cart'
    | 'common.actions.apply'
    | 'common.actions.approve'
    | 'common.actions.archive'
    | 'common.actions.back'
    | 'common.actions.backToLogin'
    | 'common.actions.book'
    | 'common.actions.cancel'
    | 'common.actions.cancel_subscription'
    | 'common.actions.checkout'
    | 'common.actions.checkout_now'
    | 'common.actions.close'
    | 'common.actions.confirm'
    | 'common.actions.continue'
    | 'common.actions.create'
    | 'common.actions.delete'
    | 'common.actions.deselect_all'
    | 'common.actions.disable'
    | 'common.actions.download'
    | 'common.actions.duplicate'
    | 'common.actions.edit'
    | 'common.actions.enable'
    | 'common.actions.export'
    | 'common.actions.filter'
    | 'common.actions.import'
    | 'common.actions.login'
    | 'common.actions.logout'
    | 'common.actions.next'
    | 'common.actions.open'
    | 'common.actions.pay'
    | 'common.actions.preview'
    | 'common.actions.previous'
    | 'common.actions.refresh'
    | 'common.actions.register'
    | 'common.actions.reject'
    | 'common.actions.remove_from_cart'
    | 'common.actions.reserve'
    | 'common.actions.reset'
    | 'common.actions.resetPassword'
    | 'common.actions.retry'
    | 'common.actions.save'
    | 'common.actions.search'
    | 'common.actions.select_all'
    | 'common.actions.send'
    | 'common.actions.share'
    | 'common.actions.sort'
    | 'common.actions.submit'
    | 'common.actions.tryAgain'
    | 'common.actions.unarchive'
    | 'common.actions.update'
    | 'common.actions.view'
    | 'common.aside.clubs'
    | 'common.aside.dashboard'
    | 'common.aside.logout'
    | 'common.aside.notifications'
    | 'common.aside.payments'
    | 'common.aside.profile'
    | 'common.aside.reports'
    | 'common.aside.reservations'
    | 'common.aside.sports'
    | 'common.aside.stadiums'
    | 'common.aside.subscriptions'
    | 'common.aside.users'
    | 'common.currency.name'
    | 'common.currency.symbol'
    | 'common.footer.address'
    | 'common.footer.allRightsReserved'
    | 'common.footer.appName'
    | 'common.footer.appSubName'
    | 'common.footer.contactPageLink'
    | 'common.footer.contactUs'
    | 'common.footer.designedFor'
    | 'common.footer.email'
    | 'common.footer.emailDescription'
    | 'common.footer.emailTitle'
    | 'common.footer.getInTouch'
    | 'common.footer.mapsUrl'
    | 'common.footer.officeDescription'
    | 'common.footer.officeTitle'
    | 'common.footer.phone'
    | 'common.footer.phoneDescription'
    | 'common.footer.phoneTitle'
    | 'common.footer.teamAlwaysHere'
    | 'common.inputs.errors.email'
    | 'common.inputs.errors.invalid'
    | 'common.inputs.errors.max'
    | 'common.inputs.errors.min'
    | 'common.inputs.errors.password_length'
    | 'common.inputs.errors.password_match'
    | 'common.inputs.errors.phone'
    | 'common.inputs.errors.required'
    | 'common.inputs.labels.address'
    | 'common.inputs.labels.capacity'
    | 'common.inputs.labels.confirm_password'
    | 'common.inputs.labels.date'
    | 'common.inputs.labels.description'
    | 'common.inputs.labels.duration'
    | 'common.inputs.labels.email'
    | 'common.inputs.labels.full_name'
    | 'common.inputs.labels.name'
    | 'common.inputs.labels.password'
    | 'common.inputs.labels.phoneNumber'
    | 'common.inputs.labels.preferred_locale'
    | 'common.inputs.labels.price'
    | 'common.inputs.labels.role'
    | 'common.inputs.labels.search'
    | 'common.inputs.labels.status'
    | 'common.inputs.labels.time'
    | 'common.inputs.placeholders.address'
    | 'common.inputs.placeholders.capacity'
    | 'common.inputs.placeholders.confirm_password'
    | 'common.inputs.placeholders.date'
    | 'common.inputs.placeholders.description'
    | 'common.inputs.placeholders.duration'
    | 'common.inputs.placeholders.email'
    | 'common.inputs.placeholders.full_name'
    | 'common.inputs.placeholders.name'
    | 'common.inputs.placeholders.password'
    | 'common.inputs.placeholders.phoneNumber'
    | 'common.inputs.placeholders.price'
    | 'common.inputs.placeholders.search'
    | 'common.inputs.placeholders.time'
    | 'common.modals.logout.message'
    | 'common.modals.logout.title'
    | 'common.months.full.april'
    | 'common.months.full.august'
    | 'common.months.full.december'
    | 'common.months.full.february'
    | 'common.months.full.january'
    | 'common.months.full.july'
    | 'common.months.full.june'
    | 'common.months.full.march'
    | 'common.months.full.may'
    | 'common.months.full.november'
    | 'common.months.full.october'
    | 'common.months.full.september'
    | 'common.months.short.apr'
    | 'common.months.short.aug'
    | 'common.months.short.dec'
    | 'common.months.short.feb'
    | 'common.months.short.jan'
    | 'common.months.short.jul'
    | 'common.months.short.jun'
    | 'common.months.short.mar'
    | 'common.months.short.may'
    | 'common.months.short.nov'
    | 'common.months.short.oct'
    | 'common.months.short.sep'
    | 'common.navigation.public.links.about'
    | 'common.navigation.public.links.contact'
    | 'common.navigation.public.links.home'
    | 'common.navigation.public.links.sectionTitle'
    | 'common.navigation.public.links.stadiums'
    | 'common.navigation.public.title'
    | 'common.notifications.close'
    | 'common.notifications.connecting'
    | 'common.notifications.live'
    | 'common.notifications.loading'
    | 'common.notifications.markAllRead'
    | 'common.notifications.markOneAsRead'
    | 'common.notifications.noNotifications'
    | 'common.notifications.offline'
    | 'common.notifications.retry'
    | 'common.notifications.title'
    | 'common.notifications.total'
    | 'common.notifications.unread'
    | 'common.notifications.viewAll'
    | 'common.theme.dark'
    | 'common.theme.description.dark'
    | 'common.theme.description.light'
    | 'common.theme.description.system'
    | 'common.theme.light'
    | 'common.theme.select'
    | 'common.theme.system'
    | 'common.time.daysAgo'
    | 'common.time.hoursAgo'
    | 'common.time.justNow'
    | 'common.time.minutesAgo'
    | 'common.time.monthsAgo'
    | 'common.time.weeksAgo'
    | 'common.time.yearsAgo'
    | 'common.toast.error.accountDeleted'
    | 'common.toast.error.accountNotApproved'
    | 'common.toast.error.accountNotVerified'
    | 'common.toast.error.creationFailed'
    | 'common.toast.error.deleteFailed'
    | 'common.toast.error.generic'
    | 'common.toast.error.loginFailed'
    | 'common.toast.error.network'
    | 'common.toast.error.registrationFailed'
    | 'common.toast.error.resetPasswordFailed'
    | 'common.toast.error.saveFailed'
    | 'common.toast.error.updateFailed'
    | 'common.toast.error.validation'
    | 'common.toast.info.loading'
    | 'common.toast.info.processing'
    | 'common.toast.info.updating'
    | 'common.toast.success.accountDeleted'
    | 'common.toast.success.accountNotApproved'
    | 'common.toast.success.accountNotVerified'
    | 'common.toast.success.created'
    | 'common.toast.success.deleted'
    | 'common.toast.success.loggedIn'
    | 'common.toast.success.loggedOut'
    | 'common.toast.success.passwordReset'
    | 'common.toast.success.passwordResetEmailSent'
    | 'common.toast.success.registered'
    | 'common.toast.success.saved'
    | 'common.toast.success.sent'
    | 'common.toast.success.updated'
    | 'common.toast.warning.confirmationRequired'
    | 'common.toast.warning.unsavedChanges'
    | 'common.user.dashboard'
    | 'common.user.dashboard_description'
    | 'common.user.logout'
    | 'common.user.logout_description'
    | 'common.user.role'
    | 'common.user.roles.admin'
    | 'common.user.roles.club'
    | 'pages.about.commitment.description'
    | 'pages.about.commitment.items.0'
    | 'pages.about.commitment.items.1'
    | 'pages.about.commitment.items.2'
    | 'pages.about.commitment.items.3'
    | 'pages.about.commitment.items.4'
    | 'pages.about.commitment.items.5'
    | 'pages.about.commitment.title'
    | 'pages.about.features.badge'
    | 'pages.about.features.description'
    | 'pages.about.features.items.access.description'
    | 'pages.about.features.items.access.title'
    | 'pages.about.features.items.availability.description'
    | 'pages.about.features.items.availability.title'
    | 'pages.about.features.items.community.description'
    | 'pages.about.features.items.community.title'
    | 'pages.about.features.items.payments.description'
    | 'pages.about.features.items.payments.title'
    | 'pages.about.features.items.quality.description'
    | 'pages.about.features.items.quality.title'
    | 'pages.about.features.items.support.description'
    | 'pages.about.features.items.support.title'
    | 'pages.about.features.title'
    | 'pages.about.hero.badge'
    | 'pages.about.hero.cta.exploreStadiums'
    | 'pages.about.hero.cta.getInTouch'
    | 'pages.about.hero.description'
    | 'pages.about.hero.highlighted'
    | 'pages.about.hero.title'
    | 'pages.about.journey.description'
    | 'pages.about.journey.timeline.2024.description'
    | 'pages.about.journey.timeline.2024.title'
    | 'pages.about.journey.timeline.2025.description'
    | 'pages.about.journey.timeline.2025.title'
    | 'pages.about.journey.timeline.2026.description'
    | 'pages.about.journey.timeline.2026.title'
    | 'pages.about.journey.title'
    | 'pages.about.metadata.description'
    | 'pages.about.metadata.keywords'
    | 'pages.about.metadata.title'
    | 'pages.about.mission.description'
    | 'pages.about.mission.title'
    | 'pages.about.mission.values.community.description'
    | 'pages.about.mission.values.community.title'
    | 'pages.about.mission.values.mission.description'
    | 'pages.about.mission.values.mission.title'
    | 'pages.about.mission.values.sustainability.description'
    | 'pages.about.mission.values.sustainability.title'
    | 'pages.about.mission.values.trust.description'
    | 'pages.about.mission.values.trust.title'
    | 'pages.about.stats.bookings.description'
    | 'pages.about.stats.bookings.label'
    | 'pages.about.stats.clubs.description'
    | 'pages.about.stats.clubs.label'
    | 'pages.about.stats.satisfaction.description'
    | 'pages.about.stats.satisfaction.label'
    | 'pages.about.stats.stadiums.description'
    | 'pages.about.stats.stadiums.label'
    | 'pages.auth.emailVerification.error.alreadyVerified'
    | 'pages.auth.emailVerification.error.alreadyVerifiedDetails'
    | 'pages.auth.emailVerification.error.contactSupport'
    | 'pages.auth.emailVerification.error.expiredToken'
    | 'pages.auth.emailVerification.error.expiredTokenDetails'
    | 'pages.auth.emailVerification.error.genericError'
    | 'pages.auth.emailVerification.error.genericErrorDetails'
    | 'pages.auth.emailVerification.error.goHome'
    | 'pages.auth.emailVerification.error.goLogin'
    | 'pages.auth.emailVerification.error.invalidToken'
    | 'pages.auth.emailVerification.error.invalidTokenDetails'
    | 'pages.auth.emailVerification.error.needHelp'
    | 'pages.auth.emailVerification.error.title'
    | 'pages.auth.emailVerification.error.tryAgain'
    | 'pages.auth.emailVerification.loading.message'
    | 'pages.auth.emailVerification.loading.steps.checkingToken'
    | 'pages.auth.emailVerification.loading.steps.preparingDashboard'
    | 'pages.auth.emailVerification.loading.steps.updatingAccount'
    | 'pages.auth.emailVerification.loading.title'
    | 'pages.auth.emailVerification.ready.message'
    | 'pages.auth.emailVerification.ready.note'
    | 'pages.auth.emailVerification.ready.title'
    | 'pages.auth.emailVerification.ready.verifyButton'
    | 'pages.auth.emailVerification.success.adminReviewTitle'
    | 'pages.auth.emailVerification.success.adminWillCall'
    | 'pages.auth.emailVerification.success.callVerificationInfo'
    | 'pages.auth.emailVerification.success.contactSupport'
    | 'pages.auth.emailVerification.success.emailConfirmed'
    | 'pages.auth.emailVerification.success.goToHomepage'
    | 'pages.auth.emailVerification.success.keepPhoneReady'
    | 'pages.auth.emailVerification.success.manualVerificationInfo'
    | 'pages.auth.emailVerification.success.message'
    | 'pages.auth.emailVerification.success.nextStepsTitle'
    | 'pages.auth.emailVerification.success.reviewTimeInfo'
    | 'pages.auth.emailVerification.success.securityCheck'
    | 'pages.auth.emailVerification.success.steps.adminCall'
    | 'pages.auth.emailVerification.success.steps.adminReview'
    | 'pages.auth.emailVerification.success.steps.approvalEmail'
    | 'pages.auth.emailVerification.success.steps.fullAccess'
    | 'pages.auth.emailVerification.success.thankYouMessage'
    | 'pages.auth.emailVerification.success.title'
    | 'pages.auth.emailVerification.success.waitForReview'
    | 'pages.auth.emailVerification.success.weWillContactYou'
    | 'pages.auth.emailVerification.title'
    | 'pages.auth.forgotPassword.description'
    | 'pages.auth.forgotPassword.instructions'
    | 'pages.auth.forgotPassword.metadata.description'
    | 'pages.auth.forgotPassword.metadata.keywords'
    | 'pages.auth.forgotPassword.metadata.title'
    | 'pages.auth.forgotPassword.no_account'
    | 'pages.auth.forgotPassword.remember_password'
    | 'pages.auth.forgotPassword.success.description'
    | 'pages.auth.forgotPassword.success.title'
    | 'pages.auth.forgotPassword.title'
    | 'pages.auth.login.dont_have_account'
    | 'pages.auth.login.forgot_password'
    | 'pages.auth.login.metadata.description'
    | 'pages.auth.login.metadata.keywords'
    | 'pages.auth.login.metadata.title'
    | 'pages.auth.login.title'
    | 'pages.auth.register.already_have_account'
    | 'pages.auth.register.forgot_password'
    | 'pages.auth.register.instructions.email_requirement'
    | 'pages.auth.register.instructions.name_requirement'
    | 'pages.auth.register.instructions.phone_requirement'
    | 'pages.auth.register.instructions.verification_process'
    | 'pages.auth.register.metadata.description'
    | 'pages.auth.register.metadata.keywords'
    | 'pages.auth.register.metadata.title'
    | 'pages.auth.register.title'
    | 'pages.auth.resetPassword.description'
    | 'pages.auth.resetPassword.instructions'
    | 'pages.auth.resetPassword.metadata.description'
    | 'pages.auth.resetPassword.metadata.keywords'
    | 'pages.auth.resetPassword.metadata.title'
    | 'pages.auth.resetPassword.remember_password'
    | 'pages.auth.resetPassword.success.description'
    | 'pages.auth.resetPassword.success.title'
    | 'pages.auth.resetPassword.title'
    | 'pages.contact.contactInfo.email.description'
    | 'pages.contact.contactInfo.email.details.0'
    | 'pages.contact.contactInfo.email.details.1'
    | 'pages.contact.contactInfo.email.title'
    | 'pages.contact.contactInfo.hours.description'
    | 'pages.contact.contactInfo.hours.details.0'
    | 'pages.contact.contactInfo.hours.details.1'
    | 'pages.contact.contactInfo.hours.title'
    | 'pages.contact.contactInfo.location.description'
    | 'pages.contact.contactInfo.location.details.0'
    | 'pages.contact.contactInfo.location.details.1'
    | 'pages.contact.contactInfo.location.title'
    | 'pages.contact.contactInfo.phone.description'
    | 'pages.contact.contactInfo.phone.details.0'
    | 'pages.contact.contactInfo.phone.details.1'
    | 'pages.contact.contactInfo.phone.title'
    | 'pages.contact.faq.description'
    | 'pages.contact.faq.questions.cancellationPolicy.answer'
    | 'pages.contact.faq.questions.cancellationPolicy.question'
    | 'pages.contact.faq.questions.multipleBookings.answer'
    | 'pages.contact.faq.questions.multipleBookings.question'
    | 'pages.contact.faq.questions.paymentMethods.answer'
    | 'pages.contact.faq.questions.paymentMethods.question'
    | 'pages.contact.faq.questions.responseTime.answer'
    | 'pages.contact.faq.questions.responseTime.question'
    | 'pages.contact.faq.title'
    | 'pages.contact.form.badge'
    | 'pages.contact.form.description'
    | 'pages.contact.form.errors.invalidEmail'
    | 'pages.contact.form.errors.invalidPhone'
    | 'pages.contact.form.errors.required'
    | 'pages.contact.form.labels.email'
    | 'pages.contact.form.labels.fullName'
    | 'pages.contact.form.labels.message'
    | 'pages.contact.form.labels.phone'
    | 'pages.contact.form.labels.subject'
    | 'pages.contact.form.note'
    | 'pages.contact.form.placeholders.email'
    | 'pages.contact.form.placeholders.fullName'
    | 'pages.contact.form.placeholders.message'
    | 'pages.contact.form.placeholders.phone'
    | 'pages.contact.form.placeholders.subject'
    | 'pages.contact.form.submitButton'
    | 'pages.contact.form.successMessage'
    | 'pages.contact.form.title'
    | 'pages.contact.hero.badge'
    | 'pages.contact.hero.description'
    | 'pages.contact.hero.highligh'
    | 'pages.contact.hero.title'
    | 'pages.contact.metadata.description'
    | 'pages.contact.metadata.keywords'
    | 'pages.contact.metadata.title'
    | 'pages.dashboard.home.charts.avgMonthly'
    | 'pages.dashboard.home.charts.legend.high'
    | 'pages.dashboard.home.charts.legend.low'
    | 'pages.dashboard.home.charts.legend.medium'
    | 'pages.dashboard.home.charts.maxRevenue'
    | 'pages.dashboard.home.charts.reservationsByMonth.description'
    | 'pages.dashboard.home.charts.reservationsByMonth.title'
    | 'pages.dashboard.home.charts.revenue'
    | 'pages.dashboard.home.charts.revenueByMonth.description'
    | 'pages.dashboard.home.charts.revenueByMonth.title'
    | 'pages.dashboard.home.charts.stadiumUtilization.description'
    | 'pages.dashboard.home.charts.stadiumUtilization.title'
    | 'pages.dashboard.home.charts.totalYear'
    | 'pages.dashboard.home.metadata.description'
    | 'pages.dashboard.home.metadata.title'
    | 'pages.dashboard.home.quickActions.addStadium'
    | 'pages.dashboard.home.quickActions.createReservation'
    | 'pages.dashboard.home.quickActions.generateReport'
    | 'pages.dashboard.home.quickActions.registerClub'
    | 'pages.dashboard.home.quickActions.sendNotification'
    | 'pages.dashboard.home.quickActions.title'
    | 'pages.dashboard.home.quickActions.viewPayments'
    | 'pages.dashboard.home.recentActivity.noActivity'
    | 'pages.dashboard.home.recentActivity.title'
    | 'pages.dashboard.home.recentActivity.types.club'
    | 'pages.dashboard.home.recentActivity.types.payment'
    | 'pages.dashboard.home.recentActivity.types.reservation'
    | 'pages.dashboard.home.recentActivity.types.subscription'
    | 'pages.dashboard.home.recentActivity.types.user'
    | 'pages.dashboard.home.recentActivity.viewAll'
    | 'pages.dashboard.home.revenueTrends.collected'
    | 'pages.dashboard.home.revenueTrends.description'
    | 'pages.dashboard.home.revenueTrends.legend.hideAll'
    | 'pages.dashboard.home.revenueTrends.legend.showAll'
    | 'pages.dashboard.home.revenueTrends.legend.toggle'
    | 'pages.dashboard.home.revenueTrends.ofTotal'
    | 'pages.dashboard.home.revenueTrends.outstanding'
    | 'pages.dashboard.home.revenueTrends.overdue'
    | 'pages.dashboard.home.revenueTrends.paid'
    | 'pages.dashboard.home.revenueTrends.singleSession'
    | 'pages.dashboard.home.revenueTrends.subscription'
    | 'pages.dashboard.home.revenueTrends.title'
    | 'pages.dashboard.home.revenueTrends.totalRevenue'
    | 'pages.dashboard.home.revenueTrends.vsLastMonth'
    | 'pages.dashboard.home.stats.activeReservations.description'
    | 'pages.dashboard.home.stats.activeReservations.title'
    | 'pages.dashboard.home.stats.avgUtilization.description'
    | 'pages.dashboard.home.stats.avgUtilization.title'
    | 'pages.dashboard.home.stats.completionRate.description'
    | 'pages.dashboard.home.stats.completionRate.title'
    | 'pages.dashboard.home.stats.monthlyRevenue.description'
    | 'pages.dashboard.home.stats.monthlyRevenue.title'
    | 'pages.dashboard.home.stats.overduePayments.description'
    | 'pages.dashboard.home.stats.overduePayments.title'
    | 'pages.dashboard.home.stats.pendingReservations.description'
    | 'pages.dashboard.home.stats.pendingReservations.title'
    | 'pages.dashboard.home.stats.subscriptions.description'
    | 'pages.dashboard.home.stats.subscriptions.title'
    | 'pages.dashboard.home.stats.totalClubs.description'
    | 'pages.dashboard.home.stats.totalClubs.title'
    | 'pages.dashboard.home.stats.totalReservations.description'
    | 'pages.dashboard.home.stats.totalReservations.title'
    | 'pages.dashboard.home.stats.totalRevenue.description'
    | 'pages.dashboard.home.stats.totalRevenue.title'
    | 'pages.dashboard.home.stats.totalStadiums.description'
    | 'pages.dashboard.home.stats.totalStadiums.title'
    | 'pages.dashboard.home.stats.totalUsers.description'
    | 'pages.dashboard.home.stats.totalUsers.title'
    | 'pages.dashboard.home.subtitle'
    | 'pages.dashboard.home.upcomingReservations.columns.amount'
    | 'pages.dashboard.home.upcomingReservations.columns.club'
    | 'pages.dashboard.home.upcomingReservations.columns.date'
    | 'pages.dashboard.home.upcomingReservations.columns.stadium'
    | 'pages.dashboard.home.upcomingReservations.columns.status'
    | 'pages.dashboard.home.upcomingReservations.columns.time'
    | 'pages.dashboard.home.upcomingReservations.noReservations'
    | 'pages.dashboard.home.upcomingReservations.title'
    | 'pages.dashboard.home.upcomingReservations.viewAll'
    | 'pages.dashboard.home.welcome'
    | 'pages.dashboard.home.yearFilter.currentYear'
    | 'pages.dashboard.home.yearFilter.label'
    | 'pages.dashboard.home.yearFilter.selectYear'
    | 'pages.error.errorId'
    | 'pages.error.goHome'
    | 'pages.error.noStackTrace'
    | 'pages.error.subtitle'
    | 'pages.error.technicalDetails'
    | 'pages.error.title'
    | 'pages.error.tryAgain'
    | 'pages.home.ctaSection.buttons.contactUs'
    | 'pages.home.ctaSection.buttons.createAccount'
    | 'pages.home.ctaSection.description'
    | 'pages.home.ctaSection.footerText'
    | 'pages.home.ctaSection.highlightedWord'
    | 'pages.home.ctaSection.title'
    | 'pages.home.featuresSection.badge'
    | 'pages.home.featuresSection.description'
    | 'pages.home.featuresSection.features.availability.description'
    | 'pages.home.featuresSection.features.availability.title'
    | 'pages.home.featuresSection.features.easyBooking.description'
    | 'pages.home.featuresSection.features.easyBooking.title'
    | 'pages.home.featuresSection.features.flexiblePayments.description'
    | 'pages.home.featuresSection.features.flexiblePayments.title'
    | 'pages.home.featuresSection.features.location.description'
    | 'pages.home.featuresSection.features.location.title'
    | 'pages.home.featuresSection.features.notifications.description'
    | 'pages.home.featuresSection.features.notifications.title'
    | 'pages.home.featuresSection.features.security.description'
    | 'pages.home.featuresSection.features.security.title'
    | 'pages.home.featuresSection.title'
    | 'pages.home.hero.badge'
    | 'pages.home.hero.createAccount'
    | 'pages.home.hero.description'
    | 'pages.home.hero.exploreStadiums'
    | 'pages.home.hero.goToDashboard'
    | 'pages.home.hero.goToMyProfile'
    | 'pages.home.hero.mainTitle.first'
    | 'pages.home.hero.mainTitle.seconde'
    | 'pages.home.hero.mainTitle.thirth'
    | 'pages.home.hero.stats.clubs'
    | 'pages.home.hero.stats.reservations'
    | 'pages.home.hero.stats.satisfaction'
    | 'pages.home.hero.stats.stadiums'
    | 'pages.home.howItWorks.badge'
    | 'pages.home.howItWorks.description'
    | 'pages.home.howItWorks.steps.book.description'
    | 'pages.home.howItWorks.steps.book.step'
    | 'pages.home.howItWorks.steps.book.title'
    | 'pages.home.howItWorks.steps.pay.description'
    | 'pages.home.howItWorks.steps.pay.step'
    | 'pages.home.howItWorks.steps.pay.title'
    | 'pages.home.howItWorks.steps.play.description'
    | 'pages.home.howItWorks.steps.play.step'
    | 'pages.home.howItWorks.steps.play.title'
    | 'pages.home.howItWorks.steps.search.description'
    | 'pages.home.howItWorks.steps.search.step'
    | 'pages.home.howItWorks.steps.search.title'
    | 'pages.home.howItWorks.title'
    | 'pages.home.metadata.description'
    | 'pages.home.metadata.keywords'
    | 'pages.home.metadata.title'
    | 'pages.home.stadiumsShowcase.badge'
    | 'pages.home.stadiumsShowcase.bookNow'
    | 'pages.home.stadiumsShowcase.currency'
    | 'pages.home.stadiumsShowcase.priceSuffix'
    | 'pages.home.stadiumsShowcase.title'
    | 'pages.home.stadiumsShowcase.viewAll'
    | 'pages.home.statsSection.description'
    | 'pages.home.statsSection.stats.clubs.description'
    | 'pages.home.statsSection.stats.clubs.label'
    | 'pages.home.statsSection.stats.reservations.description'
    | 'pages.home.statsSection.stats.reservations.label'
    | 'pages.home.statsSection.stats.satisfaction.description'
    | 'pages.home.statsSection.stats.satisfaction.label'
    | 'pages.home.statsSection.stats.stadiums.description'
    | 'pages.home.statsSection.stats.stadiums.label'
    | 'pages.home.statsSection.title'
    | 'pages.stadiums.card.addressTooltip'
    | 'pages.stadiums.card.availableSports'
    | 'pages.stadiums.card.imageTooltip'
    | 'pages.stadiums.card.mapTooltip'
    | 'pages.stadiums.card.monthly'
    | 'pages.stadiums.card.monthlyPriceTooltip'
    | 'pages.stadiums.card.monthlyTooltip'
    | 'pages.stadiums.card.otherSports'
    | 'pages.stadiums.card.perMonthShort'
    | 'pages.stadiums.card.perSession'
    | 'pages.stadiums.card.perSessionShort'
    | 'pages.stadiums.card.pricingDescription'
    | 'pages.stadiums.card.pricingTooltip'
    | 'pages.stadiums.card.reserve'
    | 'pages.stadiums.card.reserveTooltip'
    | 'pages.stadiums.card.sessionPriceTooltip'
    | 'pages.stadiums.card.sessionTooltip'
    | 'pages.stadiums.card.sportsTooltip'
    | 'pages.stadiums.card.totalSports'
    | 'pages.stadiums.card.twoOptions'
    | 'pages.stadiums.filters.clearAll'
    | 'pages.stadiums.filters.filterBySport'
    | 'pages.stadiums.filters.hideSports'
    | 'pages.stadiums.filters.noSportsFound'
    | 'pages.stadiums.filters.searchPlaceholder'
    | 'pages.stadiums.filters.selectSports'
    | 'pages.stadiums.filters.sportSearch'
    | 'pages.stadiums.filters.sportsSelected'
    | 'pages.stadiums.hero.badge'
    | 'pages.stadiums.hero.description'
    | 'pages.stadiums.hero.highlighted'
    | 'pages.stadiums.hero.title'
    | 'pages.stadiums.metadata.description'
    | 'pages.stadiums.metadata.keywords'
    | 'pages.stadiums.metadata.title'
    | 'pages.stadiums.pagination.first'
    | 'pages.stadiums.pagination.last'
    | 'pages.stadiums.pagination.next'
    | 'pages.stadiums.pagination.of'
    | 'pages.stadiums.pagination.page'
    | 'pages.stadiums.pagination.previous'
    | 'pages.stadiums.pagination.showing'
    | 'pages.stadiums.pagination.stadiums'
    | 'pages.stadiums.results.clearFilters'
    | 'pages.stadiums.results.error.message'
    | 'pages.stadiums.results.error.retry'
    | 'pages.stadiums.results.found'
    | 'pages.stadiums.results.noResults.description'
    | 'pages.stadiums.results.noResults.resetFilters'
    | 'pages.stadiums.results.noResults.title'
    | 'pages.stadiums.results.title';

export type AllTranslationKeys = TranslationKey;

export const _TranslationNamespaces = {
  "root": [
    "pages",
    "common"
  ],
  "pages": [
    "error",
    "home",
    "stadiums",
    "about",
    "contact",
    "auth",
    "dashboard"
  ],
  "pages.error": [
    "title",
    "subtitle",
    "tryAgain",
    "goHome",
    "technicalDetails",
    "errorId",
    "noStackTrace"
  ],
  "pages.home": [
    "metadata",
    "hero",
    "statsSection",
    "featuresSection",
    "stadiumsShowcase",
    "howItWorks",
    "ctaSection"
  ],
  "pages.home.metadata": [
    "title",
    "description",
    "keywords"
  ],
  "pages.home.hero": [
    "badge",
    "mainTitle",
    "description",
    "exploreStadiums",
    "goToDashboard",
    "createAccount",
    "goToMyProfile",
    "stats"
  ],
  "pages.home.hero.mainTitle": [
    "first",
    "seconde",
    "thirth"
  ],
  "pages.home.hero.stats": [
    "stadiums",
    "clubs",
    "reservations",
    "satisfaction"
  ],
  "pages.home.statsSection": [
    "title",
    "description",
    "stats"
  ],
  "pages.home.statsSection.stats": [
    "stadiums",
    "clubs",
    "reservations",
    "satisfaction"
  ],
  "pages.home.statsSection.stats.stadiums": [
    "label",
    "description"
  ],
  "pages.home.statsSection.stats.clubs": [
    "label",
    "description"
  ],
  "pages.home.statsSection.stats.reservations": [
    "label",
    "description"
  ],
  "pages.home.statsSection.stats.satisfaction": [
    "label",
    "description"
  ],
  "pages.home.featuresSection": [
    "badge",
    "title",
    "description",
    "features"
  ],
  "pages.home.featuresSection.features": [
    "easyBooking",
    "flexiblePayments",
    "notifications",
    "security",
    "availability",
    "location"
  ],
  "pages.home.featuresSection.features.easyBooking": [
    "title",
    "description"
  ],
  "pages.home.featuresSection.features.flexiblePayments": [
    "title",
    "description"
  ],
  "pages.home.featuresSection.features.notifications": [
    "title",
    "description"
  ],
  "pages.home.featuresSection.features.security": [
    "title",
    "description"
  ],
  "pages.home.featuresSection.features.availability": [
    "title",
    "description"
  ],
  "pages.home.featuresSection.features.location": [
    "title",
    "description"
  ],
  "pages.home.stadiumsShowcase": [
    "badge",
    "title",
    "viewAll",
    "priceSuffix",
    "currency",
    "bookNow"
  ],
  "pages.home.howItWorks": [
    "badge",
    "title",
    "description",
    "steps"
  ],
  "pages.home.howItWorks.steps": [
    "search",
    "book",
    "pay",
    "play"
  ],
  "pages.home.howItWorks.steps.search": [
    "step",
    "title",
    "description"
  ],
  "pages.home.howItWorks.steps.book": [
    "step",
    "title",
    "description"
  ],
  "pages.home.howItWorks.steps.pay": [
    "step",
    "title",
    "description"
  ],
  "pages.home.howItWorks.steps.play": [
    "step",
    "title",
    "description"
  ],
  "pages.home.ctaSection": [
    "title",
    "highlightedWord",
    "description",
    "buttons",
    "footerText"
  ],
  "pages.home.ctaSection.buttons": [
    "createAccount",
    "contactUs"
  ],
  "pages.stadiums": [
    "metadata",
    "hero",
    "filters",
    "results",
    "card",
    "pagination"
  ],
  "pages.stadiums.metadata": [
    "title",
    "description",
    "keywords"
  ],
  "pages.stadiums.hero": [
    "badge",
    "title",
    "highlighted",
    "description"
  ],
  "pages.stadiums.filters": [
    "searchPlaceholder",
    "filterBySport",
    "hideSports",
    "sportsSelected",
    "selectSports",
    "sportSearch",
    "noSportsFound",
    "clearAll"
  ],
  "pages.stadiums.results": [
    "title",
    "found",
    "clearFilters",
    "noResults",
    "error"
  ],
  "pages.stadiums.results.noResults": [
    "title",
    "description",
    "resetFilters"
  ],
  "pages.stadiums.results.error": [
    "message",
    "retry"
  ],
  "pages.stadiums.card": [
    "monthlyTooltip",
    "sessionTooltip",
    "imageTooltip",
    "addressTooltip",
    "sportsTooltip",
    "totalSports",
    "monthlyPriceTooltip",
    "sessionPriceTooltip",
    "pricingTooltip",
    "pricingDescription",
    "twoOptions",
    "reserveTooltip",
    "mapTooltip",
    "monthly",
    "perSession",
    "reserve",
    "otherSports",
    "availableSports",
    "perMonthShort",
    "perSessionShort"
  ],
  "pages.stadiums.pagination": [
    "showing",
    "of",
    "stadiums",
    "page",
    "next",
    "previous",
    "first",
    "last"
  ],
  "pages.about": [
    "metadata",
    "hero",
    "stats",
    "mission",
    "features",
    "journey",
    "commitment"
  ],
  "pages.about.metadata": [
    "title",
    "description",
    "keywords"
  ],
  "pages.about.hero": [
    "badge",
    "title",
    "highlighted",
    "description",
    "cta"
  ],
  "pages.about.hero.cta": [
    "exploreStadiums",
    "getInTouch"
  ],
  "pages.about.stats": [
    "stadiums",
    "clubs",
    "bookings",
    "satisfaction"
  ],
  "pages.about.stats.stadiums": [
    "label",
    "description"
  ],
  "pages.about.stats.clubs": [
    "label",
    "description"
  ],
  "pages.about.stats.bookings": [
    "label",
    "description"
  ],
  "pages.about.stats.satisfaction": [
    "label",
    "description"
  ],
  "pages.about.mission": [
    "title",
    "description",
    "values"
  ],
  "pages.about.mission.values": [
    "mission",
    "community",
    "trust",
    "sustainability"
  ],
  "pages.about.mission.values.mission": [
    "title",
    "description"
  ],
  "pages.about.mission.values.community": [
    "title",
    "description"
  ],
  "pages.about.mission.values.trust": [
    "title",
    "description"
  ],
  "pages.about.mission.values.sustainability": [
    "title",
    "description"
  ],
  "pages.about.features": [
    "badge",
    "title",
    "description",
    "items"
  ],
  "pages.about.features.items": [
    "availability",
    "payments",
    "access",
    "support",
    "quality",
    "community"
  ],
  "pages.about.features.items.availability": [
    "title",
    "description"
  ],
  "pages.about.features.items.payments": [
    "title",
    "description"
  ],
  "pages.about.features.items.access": [
    "title",
    "description"
  ],
  "pages.about.features.items.support": [
    "title",
    "description"
  ],
  "pages.about.features.items.quality": [
    "title",
    "description"
  ],
  "pages.about.features.items.community": [
    "title",
    "description"
  ],
  "pages.about.journey": [
    "title",
    "description",
    "timeline"
  ],
  "pages.about.journey.timeline": [
    "2024",
    "2025",
    "2026"
  ],
  "pages.about.journey.timeline.2024": [
    "title",
    "description"
  ],
  "pages.about.journey.timeline.2025": [
    "title",
    "description"
  ],
  "pages.about.journey.timeline.2026": [
    "title",
    "description"
  ],
  "pages.about.commitment": [
    "title",
    "description",
    "items"
  ],
  "pages.about.commitment.items": [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5"
  ],
  "pages.contact": [
    "metadata",
    "hero",
    "contactInfo",
    "form",
    "faq"
  ],
  "pages.contact.metadata": [
    "title",
    "description",
    "keywords"
  ],
  "pages.contact.hero": [
    "badge",
    "title",
    "highligh",
    "description"
  ],
  "pages.contact.contactInfo": [
    "email",
    "phone",
    "location",
    "hours"
  ],
  "pages.contact.contactInfo.email": [
    "title",
    "description",
    "details"
  ],
  "pages.contact.contactInfo.email.details": [
    "0",
    "1"
  ],
  "pages.contact.contactInfo.phone": [
    "title",
    "description",
    "details"
  ],
  "pages.contact.contactInfo.phone.details": [
    "0",
    "1"
  ],
  "pages.contact.contactInfo.location": [
    "title",
    "description",
    "details"
  ],
  "pages.contact.contactInfo.location.details": [
    "0",
    "1"
  ],
  "pages.contact.contactInfo.hours": [
    "title",
    "description",
    "details"
  ],
  "pages.contact.contactInfo.hours.details": [
    "0",
    "1"
  ],
  "pages.contact.form": [
    "badge",
    "title",
    "description",
    "labels",
    "placeholders",
    "errors",
    "submitButton",
    "successMessage",
    "note"
  ],
  "pages.contact.form.labels": [
    "fullName",
    "email",
    "phone",
    "subject",
    "message"
  ],
  "pages.contact.form.placeholders": [
    "fullName",
    "email",
    "phone",
    "subject",
    "message"
  ],
  "pages.contact.form.errors": [
    "required",
    "invalidEmail",
    "invalidPhone"
  ],
  "pages.contact.faq": [
    "title",
    "description",
    "questions"
  ],
  "pages.contact.faq.questions": [
    "responseTime",
    "multipleBookings",
    "paymentMethods",
    "cancellationPolicy"
  ],
  "pages.contact.faq.questions.responseTime": [
    "question",
    "answer"
  ],
  "pages.contact.faq.questions.multipleBookings": [
    "question",
    "answer"
  ],
  "pages.contact.faq.questions.paymentMethods": [
    "question",
    "answer"
  ],
  "pages.contact.faq.questions.cancellationPolicy": [
    "question",
    "answer"
  ],
  "pages.auth": [
    "register",
    "login",
    "emailVerification",
    "forgotPassword",
    "resetPassword"
  ],
  "pages.auth.register": [
    "metadata",
    "title",
    "already_have_account",
    "forgot_password",
    "instructions"
  ],
  "pages.auth.register.metadata": [
    "title",
    "description",
    "keywords"
  ],
  "pages.auth.register.instructions": [
    "name_requirement",
    "phone_requirement",
    "email_requirement",
    "verification_process"
  ],
  "pages.auth.login": [
    "metadata",
    "title",
    "dont_have_account",
    "forgot_password"
  ],
  "pages.auth.login.metadata": [
    "title",
    "description",
    "keywords"
  ],
  "pages.auth.emailVerification": [
    "ready",
    "title",
    "loading",
    "success",
    "error"
  ],
  "pages.auth.emailVerification.ready": [
    "title",
    "message",
    "verifyButton",
    "note"
  ],
  "pages.auth.emailVerification.loading": [
    "title",
    "message",
    "steps"
  ],
  "pages.auth.emailVerification.loading.steps": [
    "checkingToken",
    "updatingAccount",
    "preparingDashboard"
  ],
  "pages.auth.emailVerification.success": [
    "title",
    "message",
    "emailConfirmed",
    "adminReviewTitle",
    "waitForReview",
    "reviewTimeInfo",
    "adminWillCall",
    "callVerificationInfo",
    "securityCheck",
    "manualVerificationInfo",
    "nextStepsTitle",
    "steps",
    "keepPhoneReady",
    "goToHomepage",
    "contactSupport",
    "thankYouMessage",
    "weWillContactYou"
  ],
  "pages.auth.emailVerification.success.steps": [
    "adminReview",
    "adminCall",
    "approvalEmail",
    "fullAccess"
  ],
  "pages.auth.emailVerification.error": [
    "title",
    "tryAgain",
    "invalidToken",
    "invalidTokenDetails",
    "alreadyVerified",
    "alreadyVerifiedDetails",
    "expiredToken",
    "expiredTokenDetails",
    "genericError",
    "genericErrorDetails",
    "goLogin",
    "goHome",
    "contactSupport",
    "needHelp"
  ],
  "pages.auth.forgotPassword": [
    "title",
    "description",
    "instructions",
    "remember_password",
    "no_account",
    "success",
    "metadata"
  ],
  "pages.auth.forgotPassword.success": [
    "title",
    "description"
  ],
  "pages.auth.forgotPassword.metadata": [
    "title",
    "description",
    "keywords"
  ],
  "pages.auth.resetPassword": [
    "title",
    "description",
    "instructions",
    "remember_password",
    "success",
    "metadata"
  ],
  "pages.auth.resetPassword.success": [
    "title",
    "description"
  ],
  "pages.auth.resetPassword.metadata": [
    "title",
    "description",
    "keywords"
  ],
  "pages.dashboard": [
    "home"
  ],
  "pages.dashboard.home": [
    "metadata",
    "welcome",
    "subtitle",
    "yearFilter",
    "stats",
    "quickActions",
    "recentActivity",
    "upcomingReservations",
    "charts",
    "revenueTrends"
  ],
  "pages.dashboard.home.metadata": [
    "title",
    "description"
  ],
  "pages.dashboard.home.yearFilter": [
    "label",
    "selectYear",
    "currentYear"
  ],
  "pages.dashboard.home.stats": [
    "totalReservations",
    "activeReservations",
    "pendingReservations",
    "totalClubs",
    "totalStadiums",
    "totalUsers",
    "totalRevenue",
    "monthlyRevenue",
    "subscriptions",
    "overduePayments",
    "avgUtilization",
    "completionRate"
  ],
  "pages.dashboard.home.stats.totalReservations": [
    "title",
    "description"
  ],
  "pages.dashboard.home.stats.activeReservations": [
    "title",
    "description"
  ],
  "pages.dashboard.home.stats.pendingReservations": [
    "title",
    "description"
  ],
  "pages.dashboard.home.stats.totalClubs": [
    "title",
    "description"
  ],
  "pages.dashboard.home.stats.totalStadiums": [
    "title",
    "description"
  ],
  "pages.dashboard.home.stats.totalUsers": [
    "title",
    "description"
  ],
  "pages.dashboard.home.stats.totalRevenue": [
    "title",
    "description"
  ],
  "pages.dashboard.home.stats.monthlyRevenue": [
    "title",
    "description"
  ],
  "pages.dashboard.home.stats.subscriptions": [
    "title",
    "description"
  ],
  "pages.dashboard.home.stats.overduePayments": [
    "title",
    "description"
  ],
  "pages.dashboard.home.stats.avgUtilization": [
    "title",
    "description"
  ],
  "pages.dashboard.home.stats.completionRate": [
    "title",
    "description"
  ],
  "pages.dashboard.home.quickActions": [
    "title",
    "createReservation",
    "addStadium",
    "registerClub",
    "viewPayments",
    "sendNotification",
    "generateReport"
  ],
  "pages.dashboard.home.recentActivity": [
    "title",
    "viewAll",
    "noActivity",
    "types"
  ],
  "pages.dashboard.home.recentActivity.types": [
    "reservation",
    "payment",
    "subscription",
    "user",
    "club"
  ],
  "pages.dashboard.home.upcomingReservations": [
    "title",
    "viewAll",
    "noReservations",
    "columns"
  ],
  "pages.dashboard.home.upcomingReservations.columns": [
    "stadium",
    "club",
    "date",
    "time",
    "status",
    "amount"
  ],
  "pages.dashboard.home.charts": [
    "revenue",
    "maxRevenue",
    "avgMonthly",
    "totalYear",
    "legend",
    "reservationsByMonth",
    "revenueByMonth",
    "stadiumUtilization"
  ],
  "pages.dashboard.home.charts.legend": [
    "low",
    "medium",
    "high"
  ],
  "pages.dashboard.home.charts.reservationsByMonth": [
    "title",
    "description"
  ],
  "pages.dashboard.home.charts.revenueByMonth": [
    "title",
    "description"
  ],
  "pages.dashboard.home.charts.stadiumUtilization": [
    "title",
    "description"
  ],
  "pages.dashboard.home.revenueTrends": [
    "title",
    "description",
    "totalRevenue",
    "subscription",
    "singleSession",
    "paid",
    "overdue",
    "vsLastMonth",
    "ofTotal",
    "collected",
    "outstanding",
    "legend"
  ],
  "pages.dashboard.home.revenueTrends.legend": [
    "toggle",
    "showAll",
    "hideAll"
  ],
  "common": [
    "actions",
    "theme",
    "user",
    "modals",
    "navigation",
    "inputs",
    "notifications",
    "toast",
    "footer",
    "aside",
    "currency",
    "months",
    "time"
  ],
  "common.actions": [
    "reserve",
    "search",
    "login",
    "register",
    "logout",
    "save",
    "cancel",
    "confirm",
    "delete",
    "edit",
    "view",
    "book",
    "checkout",
    "checkout_now",
    "continue",
    "back",
    "filter",
    "sort",
    "download",
    "create",
    "update",
    "duplicate",
    "archive",
    "unarchive",
    "enable",
    "disable",
    "export",
    "import",
    "preview",
    "share",
    "send",
    "cancel_subscription",
    "retry",
    "refresh",
    "close",
    "open",
    "select_all",
    "deselect_all",
    "pay",
    "add_to_cart",
    "remove_from_cart",
    "apply",
    "approve",
    "reject",
    "submit",
    "next",
    "previous",
    "reset",
    "resetPassword",
    "backToLogin",
    "tryAgain"
  ],
  "common.theme": [
    "light",
    "dark",
    "system",
    "select",
    "description"
  ],
  "common.theme.description": [
    "light",
    "dark",
    "system"
  ],
  "common.user": [
    "dashboard",
    "dashboard_description",
    "logout",
    "logout_description",
    "role",
    "roles"
  ],
  "common.user.roles": [
    "admin",
    "club"
  ],
  "common.modals": [
    "logout"
  ],
  "common.modals.logout": [
    "title",
    "message"
  ],
  "common.navigation": [
    "public"
  ],
  "common.navigation.public": [
    "title",
    "links"
  ],
  "common.navigation.public.links": [
    "home",
    "stadiums",
    "about",
    "contact",
    "sectionTitle"
  ],
  "common.inputs": [
    "labels",
    "placeholders",
    "errors"
  ],
  "common.inputs.labels": [
    "full_name",
    "email",
    "password",
    "phoneNumber",
    "confirm_password",
    "role",
    "preferred_locale",
    "search",
    "name",
    "description",
    "address",
    "capacity",
    "price",
    "date",
    "time",
    "duration",
    "status"
  ],
  "common.inputs.placeholders": [
    "full_name",
    "email",
    "password",
    "phoneNumber",
    "confirm_password",
    "search",
    "name",
    "description",
    "address",
    "capacity",
    "price",
    "date",
    "time",
    "duration"
  ],
  "common.inputs.errors": [
    "required",
    "email",
    "password_length",
    "password_match",
    "phone",
    "min",
    "max",
    "invalid"
  ],
  "common.notifications": [
    "title",
    "unread",
    "markAllRead",
    "markOneAsRead",
    "loading",
    "retry",
    "noNotifications",
    "live",
    "connecting",
    "offline",
    "total",
    "viewAll",
    "close"
  ],
  "common.toast": [
    "success",
    "error",
    "info",
    "warning"
  ],
  "common.toast.success": [
    "created",
    "updated",
    "deleted",
    "saved",
    "registered",
    "loggedIn",
    "loggedOut",
    "sent",
    "passwordResetEmailSent",
    "accountDeleted",
    "accountNotVerified",
    "accountNotApproved",
    "passwordReset"
  ],
  "common.toast.error": [
    "creationFailed",
    "updateFailed",
    "deleteFailed",
    "saveFailed",
    "registrationFailed",
    "loginFailed",
    "generic",
    "network",
    "validation",
    "resetPasswordFailed"
  ],
  "common.toast.info": [
    "loading",
    "processing",
    "updating"
  ],
  "common.toast.warning": [
    "unsavedChanges",
    "confirmationRequired"
  ],
  "common.footer": [
    "emailTitle",
    "emailDescription",
    "email",
    "officeTitle",
    "officeDescription",
    "address",
    "mapsUrl",
    "phoneTitle",
    "phoneDescription",
    "phone",
    "contactUs",
    "getInTouch",
    "teamAlwaysHere",
    "contactPageLink",
    "allRightsReserved",
    "designedFor",
    "appName",
    "appSubName"
  ],
  "common.aside": [
    "dashboard",
    "clubs",
    "stadiums",
    "reservations",
    "payments",
    "subscriptions",
    "users",
    "sports",
    "reports",
    "notifications",
    "profile",
    "logout"
  ],
  "common.currency": [
    "symbol",
    "name"
  ],
  "common.months": [
    "short",
    "full"
  ],
  "common.months.short": [
    "jan",
    "feb",
    "mar",
    "apr",
    "may",
    "jun",
    "jul",
    "aug",
    "sep",
    "oct",
    "nov",
    "dec"
  ],
  "common.months.full": [
    "january",
    "february",
    "march",
    "april",
    "may",
    "june",
    "july",
    "august",
    "september",
    "october",
    "november",
    "december"
  ],
  "common.time": [
    "justNow",
    "minutesAgo",
    "hoursAgo",
    "daysAgo",
    "weeksAgo",
    "monthsAgo",
    "yearsAgo"
  ]
} as const;

export type TranslationNamespace = keyof typeof _TranslationNamespaces;
