// ⚠️ AUTO-GENERATED — DO NOT EDIT
// Generated by scripts/generate-i18n.ts

/* ---------------- Translation keys ---------------- */
export type TranslationKey =
    | 'common.actions.add_to_cart'
    | 'common.actions.apply'
    | 'common.actions.approve'
    | 'common.actions.archive'
    | 'common.actions.back'
    | 'common.actions.book'
    | 'common.actions.cancel'
    | 'common.actions.cancel_subscription'
    | 'common.actions.checkout'
    | 'common.actions.checkout_now'
    | 'common.actions.close'
    | 'common.actions.confirm'
    | 'common.actions.continue'
    | 'common.actions.create'
    | 'common.actions.delete'
    | 'common.actions.deselect_all'
    | 'common.actions.disable'
    | 'common.actions.download'
    | 'common.actions.duplicate'
    | 'common.actions.edit'
    | 'common.actions.enable'
    | 'common.actions.export'
    | 'common.actions.filter'
    | 'common.actions.import'
    | 'common.actions.login'
    | 'common.actions.logout'
    | 'common.actions.next'
    | 'common.actions.open'
    | 'common.actions.pay'
    | 'common.actions.preview'
    | 'common.actions.previous'
    | 'common.actions.refresh'
    | 'common.actions.register'
    | 'common.actions.reject'
    | 'common.actions.remove_from_cart'
    | 'common.actions.reserve'
    | 'common.actions.reset'
    | 'common.actions.retry'
    | 'common.actions.save'
    | 'common.actions.search'
    | 'common.actions.select_all'
    | 'common.actions.send'
    | 'common.actions.share'
    | 'common.actions.sort'
    | 'common.actions.submit'
    | 'common.actions.unarchive'
    | 'common.actions.update'
    | 'common.actions.view'
    | 'common.inputs.errors.email'
    | 'common.inputs.errors.invalid'
    | 'common.inputs.errors.max'
    | 'common.inputs.errors.min'
    | 'common.inputs.errors.password_length'
    | 'common.inputs.errors.password_match'
    | 'common.inputs.errors.phone'
    | 'common.inputs.errors.required'
    | 'common.inputs.labels.address'
    | 'common.inputs.labels.capacity'
    | 'common.inputs.labels.confirm_password'
    | 'common.inputs.labels.date'
    | 'common.inputs.labels.description'
    | 'common.inputs.labels.duration'
    | 'common.inputs.labels.email'
    | 'common.inputs.labels.full_name'
    | 'common.inputs.labels.name'
    | 'common.inputs.labels.password'
    | 'common.inputs.labels.phoneNumber'
    | 'common.inputs.labels.preferred_locale'
    | 'common.inputs.labels.price'
    | 'common.inputs.labels.role'
    | 'common.inputs.labels.search'
    | 'common.inputs.labels.status'
    | 'common.inputs.labels.time'
    | 'common.inputs.placeholders.address'
    | 'common.inputs.placeholders.capacity'
    | 'common.inputs.placeholders.confirm_password'
    | 'common.inputs.placeholders.date'
    | 'common.inputs.placeholders.description'
    | 'common.inputs.placeholders.duration'
    | 'common.inputs.placeholders.email'
    | 'common.inputs.placeholders.full_name'
    | 'common.inputs.placeholders.name'
    | 'common.inputs.placeholders.password'
    | 'common.inputs.placeholders.phoneNumber'
    | 'common.inputs.placeholders.price'
    | 'common.inputs.placeholders.search'
    | 'common.inputs.placeholders.time'
    | 'common.modals.logout.message'
    | 'common.modals.logout.title'
    | 'common.navigation.public.links.about'
    | 'common.navigation.public.links.contact'
    | 'common.navigation.public.links.home'
    | 'common.navigation.public.links.sectionTitle'
    | 'common.navigation.public.links.stadiums'
    | 'common.navigation.public.title'
    | 'common.notifications.close'
    | 'common.notifications.connecting'
    | 'common.notifications.live'
    | 'common.notifications.loading'
    | 'common.notifications.markAllRead'
    | 'common.notifications.markOneAsRead'
    | 'common.notifications.noNotifications'
    | 'common.notifications.offline'
    | 'common.notifications.retry'
    | 'common.notifications.title'
    | 'common.notifications.total'
    | 'common.notifications.unread'
    | 'common.notifications.viewAll'
    | 'common.theme.dark'
    | 'common.theme.description.dark'
    | 'common.theme.description.light'
    | 'common.theme.description.system'
    | 'common.theme.light'
    | 'common.theme.select'
    | 'common.theme.system'
    | 'common.toast.error.creationFailed'
    | 'common.toast.error.deleteFailed'
    | 'common.toast.error.generic'
    | 'common.toast.error.loginFailed'
    | 'common.toast.error.network'
    | 'common.toast.error.registrationFailed'
    | 'common.toast.error.saveFailed'
    | 'common.toast.error.updateFailed'
    | 'common.toast.error.validation'
    | 'common.toast.info.loading'
    | 'common.toast.info.processing'
    | 'common.toast.info.updating'
    | 'common.toast.success.created'
    | 'common.toast.success.deleted'
    | 'common.toast.success.loggedIn'
    | 'common.toast.success.loggedOut'
    | 'common.toast.success.registered'
    | 'common.toast.success.saved'
    | 'common.toast.success.sent'
    | 'common.toast.success.updated'
    | 'common.toast.warning.confirmationRequired'
    | 'common.toast.warning.unsavedChanges'
    | 'common.user.dashboard'
    | 'common.user.logout'
    | 'common.user.profile'
    | 'common.user.role'
    | 'common.user.roles.admin'
    | 'common.user.roles.club'
    | 'pages.about.metadata.description'
    | 'pages.about.metadata.keywords'
    | 'pages.about.metadata.title'
    | 'pages.auth.emailVerification.error.alreadyVerified'
    | 'pages.auth.emailVerification.error.alreadyVerifiedDetails'
    | 'pages.auth.emailVerification.error.contactSupport'
    | 'pages.auth.emailVerification.error.expiredToken'
    | 'pages.auth.emailVerification.error.expiredTokenDetails'
    | 'pages.auth.emailVerification.error.genericError'
    | 'pages.auth.emailVerification.error.genericErrorDetails'
    | 'pages.auth.emailVerification.error.goHome'
    | 'pages.auth.emailVerification.error.goLogin'
    | 'pages.auth.emailVerification.error.invalidToken'
    | 'pages.auth.emailVerification.error.invalidTokenDetails'
    | 'pages.auth.emailVerification.error.needHelp'
    | 'pages.auth.emailVerification.error.title'
    | 'pages.auth.emailVerification.error.tryAgain'
    | 'pages.auth.emailVerification.loading.message'
    | 'pages.auth.emailVerification.loading.steps.checkingToken'
    | 'pages.auth.emailVerification.loading.steps.preparingDashboard'
    | 'pages.auth.emailVerification.loading.steps.updatingAccount'
    | 'pages.auth.emailVerification.loading.title'
    | 'pages.auth.emailVerification.ready.message'
    | 'pages.auth.emailVerification.ready.note'
    | 'pages.auth.emailVerification.ready.title'
    | 'pages.auth.emailVerification.ready.verifyButton'
    | 'pages.auth.emailVerification.success.adminReviewTitle'
    | 'pages.auth.emailVerification.success.adminWillCall'
    | 'pages.auth.emailVerification.success.callVerificationInfo'
    | 'pages.auth.emailVerification.success.contactSupport'
    | 'pages.auth.emailVerification.success.emailConfirmed'
    | 'pages.auth.emailVerification.success.goToHomepage'
    | 'pages.auth.emailVerification.success.keepPhoneReady'
    | 'pages.auth.emailVerification.success.manualVerificationInfo'
    | 'pages.auth.emailVerification.success.message'
    | 'pages.auth.emailVerification.success.nextStepsTitle'
    | 'pages.auth.emailVerification.success.reviewTimeInfo'
    | 'pages.auth.emailVerification.success.securityCheck'
    | 'pages.auth.emailVerification.success.steps.adminCall'
    | 'pages.auth.emailVerification.success.steps.adminReview'
    | 'pages.auth.emailVerification.success.steps.approvalEmail'
    | 'pages.auth.emailVerification.success.steps.fullAccess'
    | 'pages.auth.emailVerification.success.thankYouMessage'
    | 'pages.auth.emailVerification.success.title'
    | 'pages.auth.emailVerification.success.waitForReview'
    | 'pages.auth.emailVerification.success.weWillContactYou'
    | 'pages.auth.emailVerification.title'
    | 'pages.auth.login.dont_have_account'
    | 'pages.auth.login.forgot_password'
    | 'pages.auth.login.metadata.description'
    | 'pages.auth.login.metadata.keywords'
    | 'pages.auth.login.metadata.title'
    | 'pages.auth.login.title'
    | 'pages.auth.register.already_have_account'
    | 'pages.auth.register.forgot_password'
    | 'pages.auth.register.instructions.email_requirement'
    | 'pages.auth.register.instructions.name_requirement'
    | 'pages.auth.register.instructions.phone_requirement'
    | 'pages.auth.register.instructions.verification_process'
    | 'pages.auth.register.metadata.description'
    | 'pages.auth.register.metadata.keywords'
    | 'pages.auth.register.metadata.title'
    | 'pages.auth.register.title'
    | 'pages.contact.metadata.description'
    | 'pages.contact.metadata.keywords'
    | 'pages.contact.metadata.title'
    | 'pages.error.errorId'
    | 'pages.error.goHome'
    | 'pages.error.noStackTrace'
    | 'pages.error.subtitle'
    | 'pages.error.technicalDetails'
    | 'pages.error.title'
    | 'pages.error.tryAgain'
    | 'pages.home.ctaSection.buttons.contactUs'
    | 'pages.home.ctaSection.buttons.createAccount'
    | 'pages.home.ctaSection.description'
    | 'pages.home.ctaSection.footerText'
    | 'pages.home.ctaSection.highlightedWord'
    | 'pages.home.ctaSection.title'
    | 'pages.home.featuresSection.badge'
    | 'pages.home.featuresSection.description'
    | 'pages.home.featuresSection.features.availability.description'
    | 'pages.home.featuresSection.features.availability.title'
    | 'pages.home.featuresSection.features.easyBooking.description'
    | 'pages.home.featuresSection.features.easyBooking.title'
    | 'pages.home.featuresSection.features.flexiblePayments.description'
    | 'pages.home.featuresSection.features.flexiblePayments.title'
    | 'pages.home.featuresSection.features.location.description'
    | 'pages.home.featuresSection.features.location.title'
    | 'pages.home.featuresSection.features.notifications.description'
    | 'pages.home.featuresSection.features.notifications.title'
    | 'pages.home.featuresSection.features.security.description'
    | 'pages.home.featuresSection.features.security.title'
    | 'pages.home.featuresSection.title'
    | 'pages.home.hero.badge'
    | 'pages.home.hero.description'
    | 'pages.home.hero.exploreStadiums'
    | 'pages.home.hero.howItWorks'
    | 'pages.home.hero.mainTitle.first'
    | 'pages.home.hero.mainTitle.seconde'
    | 'pages.home.hero.mainTitle.thirth'
    | 'pages.home.hero.stats.clubs'
    | 'pages.home.hero.stats.reservations'
    | 'pages.home.hero.stats.satisfaction'
    | 'pages.home.hero.stats.stadiums'
    | 'pages.home.howItWorks.badge'
    | 'pages.home.howItWorks.description'
    | 'pages.home.howItWorks.steps.book.description'
    | 'pages.home.howItWorks.steps.book.step'
    | 'pages.home.howItWorks.steps.book.title'
    | 'pages.home.howItWorks.steps.pay.description'
    | 'pages.home.howItWorks.steps.pay.step'
    | 'pages.home.howItWorks.steps.pay.title'
    | 'pages.home.howItWorks.steps.play.description'
    | 'pages.home.howItWorks.steps.play.step'
    | 'pages.home.howItWorks.steps.play.title'
    | 'pages.home.howItWorks.steps.search.description'
    | 'pages.home.howItWorks.steps.search.step'
    | 'pages.home.howItWorks.steps.search.title'
    | 'pages.home.howItWorks.title'
    | 'pages.home.metadata.description'
    | 'pages.home.metadata.keywords'
    | 'pages.home.metadata.title'
    | 'pages.home.stadiumsShowcase.badge'
    | 'pages.home.stadiumsShowcase.currency'
    | 'pages.home.stadiumsShowcase.priceSuffix'
    | 'pages.home.stadiumsShowcase.title'
    | 'pages.home.stadiumsShowcase.viewAll'
    | 'pages.home.statsSection.description'
    | 'pages.home.statsSection.stats.clubs.description'
    | 'pages.home.statsSection.stats.clubs.label'
    | 'pages.home.statsSection.stats.reservations.description'
    | 'pages.home.statsSection.stats.reservations.label'
    | 'pages.home.statsSection.stats.satisfaction.description'
    | 'pages.home.statsSection.stats.satisfaction.label'
    | 'pages.home.statsSection.stats.stadiums.description'
    | 'pages.home.statsSection.stats.stadiums.label'
    | 'pages.home.statsSection.title'
    | 'pages.stadiums.card.addressTooltip'
    | 'pages.stadiums.card.availableSports'
    | 'pages.stadiums.card.imageTooltip'
    | 'pages.stadiums.card.mapTooltip'
    | 'pages.stadiums.card.monthly'
    | 'pages.stadiums.card.monthlyPriceTooltip'
    | 'pages.stadiums.card.monthlyTooltip'
    | 'pages.stadiums.card.otherSports'
    | 'pages.stadiums.card.perSession'
    | 'pages.stadiums.card.pricingDescription'
    | 'pages.stadiums.card.pricingTooltip'
    | 'pages.stadiums.card.reserve'
    | 'pages.stadiums.card.reserveTooltip'
    | 'pages.stadiums.card.sessionPriceTooltip'
    | 'pages.stadiums.card.sessionTooltip'
    | 'pages.stadiums.card.sportsTooltip'
    | 'pages.stadiums.card.totalSports'
    | 'pages.stadiums.card.twoOptions'
    | 'pages.stadiums.filters.clearAll'
    | 'pages.stadiums.filters.filterBySport'
    | 'pages.stadiums.filters.hideSports'
    | 'pages.stadiums.filters.noSportsFound'
    | 'pages.stadiums.filters.searchPlaceholder'
    | 'pages.stadiums.filters.selectSports'
    | 'pages.stadiums.filters.sportSearch'
    | 'pages.stadiums.filters.sportsSelected'
    | 'pages.stadiums.hero.badge'
    | 'pages.stadiums.hero.description'
    | 'pages.stadiums.hero.highlighted'
    | 'pages.stadiums.hero.title'
    | 'pages.stadiums.metadata.description'
    | 'pages.stadiums.metadata.keywords'
    | 'pages.stadiums.metadata.title'
    | 'pages.stadiums.pagination.first'
    | 'pages.stadiums.pagination.last'
    | 'pages.stadiums.pagination.next'
    | 'pages.stadiums.pagination.of'
    | 'pages.stadiums.pagination.page'
    | 'pages.stadiums.pagination.previous'
    | 'pages.stadiums.pagination.showing'
    | 'pages.stadiums.pagination.stadiums'
    | 'pages.stadiums.results.clearFilters'
    | 'pages.stadiums.results.error.message'
    | 'pages.stadiums.results.error.retry'
    | 'pages.stadiums.results.found'
    | 'pages.stadiums.results.noResults.description'
    | 'pages.stadiums.results.noResults.resetFilters'
    | 'pages.stadiums.results.noResults.title'
    | 'pages.stadiums.results.title';

export type AllTranslationKeys = TranslationKey;

export const _TranslationNamespaces = {
  "root": [
    "pages",
    "common"
  ],
  "pages": [
    "error",
    "home",
    "stadiums",
    "about",
    "contact",
    "auth"
  ],
  "pages.error": [
    "title",
    "subtitle",
    "tryAgain",
    "goHome",
    "technicalDetails",
    "errorId",
    "noStackTrace"
  ],
  "pages.home": [
    "metadata",
    "hero",
    "statsSection",
    "featuresSection",
    "stadiumsShowcase",
    "howItWorks",
    "ctaSection"
  ],
  "pages.home.metadata": [
    "title",
    "description",
    "keywords"
  ],
  "pages.home.hero": [
    "badge",
    "mainTitle",
    "description",
    "exploreStadiums",
    "howItWorks",
    "stats"
  ],
  "pages.home.hero.mainTitle": [
    "first",
    "seconde",
    "thirth"
  ],
  "pages.home.hero.stats": [
    "stadiums",
    "clubs",
    "reservations",
    "satisfaction"
  ],
  "pages.home.statsSection": [
    "title",
    "description",
    "stats"
  ],
  "pages.home.statsSection.stats": [
    "stadiums",
    "clubs",
    "reservations",
    "satisfaction"
  ],
  "pages.home.statsSection.stats.stadiums": [
    "label",
    "description"
  ],
  "pages.home.statsSection.stats.clubs": [
    "label",
    "description"
  ],
  "pages.home.statsSection.stats.reservations": [
    "label",
    "description"
  ],
  "pages.home.statsSection.stats.satisfaction": [
    "label",
    "description"
  ],
  "pages.home.featuresSection": [
    "badge",
    "title",
    "description",
    "features"
  ],
  "pages.home.featuresSection.features": [
    "easyBooking",
    "flexiblePayments",
    "notifications",
    "security",
    "availability",
    "location"
  ],
  "pages.home.featuresSection.features.easyBooking": [
    "title",
    "description"
  ],
  "pages.home.featuresSection.features.flexiblePayments": [
    "title",
    "description"
  ],
  "pages.home.featuresSection.features.notifications": [
    "title",
    "description"
  ],
  "pages.home.featuresSection.features.security": [
    "title",
    "description"
  ],
  "pages.home.featuresSection.features.availability": [
    "title",
    "description"
  ],
  "pages.home.featuresSection.features.location": [
    "title",
    "description"
  ],
  "pages.home.stadiumsShowcase": [
    "badge",
    "title",
    "viewAll",
    "priceSuffix",
    "currency"
  ],
  "pages.home.howItWorks": [
    "badge",
    "title",
    "description",
    "steps"
  ],
  "pages.home.howItWorks.steps": [
    "search",
    "book",
    "pay",
    "play"
  ],
  "pages.home.howItWorks.steps.search": [
    "step",
    "title",
    "description"
  ],
  "pages.home.howItWorks.steps.book": [
    "step",
    "title",
    "description"
  ],
  "pages.home.howItWorks.steps.pay": [
    "step",
    "title",
    "description"
  ],
  "pages.home.howItWorks.steps.play": [
    "step",
    "title",
    "description"
  ],
  "pages.home.ctaSection": [
    "title",
    "highlightedWord",
    "description",
    "buttons",
    "footerText"
  ],
  "pages.home.ctaSection.buttons": [
    "createAccount",
    "contactUs"
  ],
  "pages.stadiums": [
    "metadata",
    "hero",
    "filters",
    "results",
    "card",
    "pagination"
  ],
  "pages.stadiums.metadata": [
    "title",
    "description",
    "keywords"
  ],
  "pages.stadiums.hero": [
    "badge",
    "title",
    "highlighted",
    "description"
  ],
  "pages.stadiums.filters": [
    "searchPlaceholder",
    "filterBySport",
    "hideSports",
    "sportsSelected",
    "selectSports",
    "sportSearch",
    "noSportsFound",
    "clearAll"
  ],
  "pages.stadiums.results": [
    "title",
    "found",
    "clearFilters",
    "noResults",
    "error"
  ],
  "pages.stadiums.results.noResults": [
    "title",
    "description",
    "resetFilters"
  ],
  "pages.stadiums.results.error": [
    "message",
    "retry"
  ],
  "pages.stadiums.card": [
    "monthlyTooltip",
    "sessionTooltip",
    "imageTooltip",
    "addressTooltip",
    "sportsTooltip",
    "totalSports",
    "monthlyPriceTooltip",
    "sessionPriceTooltip",
    "pricingTooltip",
    "pricingDescription",
    "twoOptions",
    "reserveTooltip",
    "mapTooltip",
    "monthly",
    "perSession",
    "reserve",
    "otherSports",
    "availableSports"
  ],
  "pages.stadiums.pagination": [
    "showing",
    "of",
    "stadiums",
    "page",
    "next",
    "previous",
    "first",
    "last"
  ],
  "pages.about": [
    "metadata"
  ],
  "pages.about.metadata": [
    "title",
    "description",
    "keywords"
  ],
  "pages.contact": [
    "metadata"
  ],
  "pages.contact.metadata": [
    "title",
    "description",
    "keywords"
  ],
  "pages.auth": [
    "register",
    "login",
    "emailVerification"
  ],
  "pages.auth.register": [
    "metadata",
    "title",
    "already_have_account",
    "forgot_password",
    "instructions"
  ],
  "pages.auth.register.metadata": [
    "title",
    "description",
    "keywords"
  ],
  "pages.auth.register.instructions": [
    "name_requirement",
    "phone_requirement",
    "email_requirement",
    "verification_process"
  ],
  "pages.auth.login": [
    "metadata",
    "title",
    "dont_have_account",
    "forgot_password"
  ],
  "pages.auth.login.metadata": [
    "title",
    "description",
    "keywords"
  ],
  "pages.auth.emailVerification": [
    "ready",
    "title",
    "loading",
    "success",
    "error"
  ],
  "pages.auth.emailVerification.ready": [
    "title",
    "message",
    "verifyButton",
    "note"
  ],
  "pages.auth.emailVerification.loading": [
    "title",
    "message",
    "steps"
  ],
  "pages.auth.emailVerification.loading.steps": [
    "checkingToken",
    "updatingAccount",
    "preparingDashboard"
  ],
  "pages.auth.emailVerification.success": [
    "title",
    "message",
    "emailConfirmed",
    "adminReviewTitle",
    "waitForReview",
    "reviewTimeInfo",
    "adminWillCall",
    "callVerificationInfo",
    "securityCheck",
    "manualVerificationInfo",
    "nextStepsTitle",
    "steps",
    "keepPhoneReady",
    "goToHomepage",
    "contactSupport",
    "thankYouMessage",
    "weWillContactYou"
  ],
  "pages.auth.emailVerification.success.steps": [
    "adminReview",
    "adminCall",
    "approvalEmail",
    "fullAccess"
  ],
  "pages.auth.emailVerification.error": [
    "title",
    "tryAgain",
    "invalidToken",
    "invalidTokenDetails",
    "alreadyVerified",
    "alreadyVerifiedDetails",
    "expiredToken",
    "expiredTokenDetails",
    "genericError",
    "genericErrorDetails",
    "goLogin",
    "goHome",
    "contactSupport",
    "needHelp"
  ],
  "common": [
    "actions",
    "theme",
    "user",
    "modals",
    "navigation",
    "inputs",
    "notifications",
    "toast"
  ],
  "common.actions": [
    "reserve",
    "search",
    "login",
    "register",
    "logout",
    "save",
    "cancel",
    "confirm",
    "delete",
    "edit",
    "view",
    "book",
    "checkout",
    "checkout_now",
    "continue",
    "back",
    "filter",
    "sort",
    "download",
    "create",
    "update",
    "duplicate",
    "archive",
    "unarchive",
    "enable",
    "disable",
    "export",
    "import",
    "preview",
    "share",
    "send",
    "cancel_subscription",
    "retry",
    "refresh",
    "close",
    "open",
    "select_all",
    "deselect_all",
    "pay",
    "add_to_cart",
    "remove_from_cart",
    "apply",
    "approve",
    "reject",
    "submit",
    "next",
    "previous",
    "reset"
  ],
  "common.theme": [
    "light",
    "dark",
    "system",
    "select",
    "description"
  ],
  "common.theme.description": [
    "light",
    "dark",
    "system"
  ],
  "common.user": [
    "dashboard",
    "profile",
    "logout",
    "role",
    "roles"
  ],
  "common.user.roles": [
    "admin",
    "club"
  ],
  "common.modals": [
    "logout"
  ],
  "common.modals.logout": [
    "title",
    "message"
  ],
  "common.navigation": [
    "public"
  ],
  "common.navigation.public": [
    "title",
    "links"
  ],
  "common.navigation.public.links": [
    "home",
    "stadiums",
    "about",
    "contact",
    "sectionTitle"
  ],
  "common.inputs": [
    "labels",
    "placeholders",
    "errors"
  ],
  "common.inputs.labels": [
    "full_name",
    "email",
    "password",
    "phoneNumber",
    "confirm_password",
    "role",
    "preferred_locale",
    "search",
    "name",
    "description",
    "address",
    "capacity",
    "price",
    "date",
    "time",
    "duration",
    "status"
  ],
  "common.inputs.placeholders": [
    "full_name",
    "email",
    "password",
    "phoneNumber",
    "confirm_password",
    "search",
    "name",
    "description",
    "address",
    "capacity",
    "price",
    "date",
    "time",
    "duration"
  ],
  "common.inputs.errors": [
    "required",
    "email",
    "password_length",
    "password_match",
    "phone",
    "min",
    "max",
    "invalid"
  ],
  "common.notifications": [
    "title",
    "unread",
    "markAllRead",
    "markOneAsRead",
    "loading",
    "retry",
    "noNotifications",
    "live",
    "connecting",
    "offline",
    "total",
    "viewAll",
    "close"
  ],
  "common.toast": [
    "success",
    "error",
    "info",
    "warning"
  ],
  "common.toast.success": [
    "created",
    "updated",
    "deleted",
    "saved",
    "registered",
    "loggedIn",
    "loggedOut",
    "sent"
  ],
  "common.toast.error": [
    "creationFailed",
    "updateFailed",
    "deleteFailed",
    "saveFailed",
    "registrationFailed",
    "loginFailed",
    "generic",
    "network",
    "validation"
  ],
  "common.toast.info": [
    "loading",
    "processing",
    "updating"
  ],
  "common.toast.warning": [
    "unsavedChanges",
    "confirmationRequired"
  ]
} as const;

export type TranslationNamespace = keyof typeof _TranslationNamespaces;
