// ⚠️ AUTO-GENERATED — DO NOT EDIT
// Generated by scripts/generate-i18n.ts

declare global {
  export type TranslationKey =
    | 'common.actions.back'
    | 'common.actions.book'
    | 'common.actions.cancel'
    | 'common.actions.checkout'
    | 'common.actions.confirm'
    | 'common.actions.continue'
    | 'common.actions.delete'
    | 'common.actions.download'
    | 'common.actions.edit'
    | 'common.actions.filter'
    | 'common.actions.login'
    | 'common.actions.logout'
    | 'common.actions.register'
    | 'common.actions.reserve'
    | 'common.actions.save'
    | 'common.actions.search'
    | 'common.actions.share'
    | 'common.actions.sort'
    | 'common.actions.view'
    | 'common.modals.logout.cancel'
    | 'common.modals.logout.confirm'
    | 'common.modals.logout.message'
    | 'common.modals.logout.title'
    | 'common.navigation.public.links.about'
    | 'common.navigation.public.links.contact'
    | 'common.navigation.public.links.home'
    | 'common.navigation.public.links.sectionTitle'
    | 'common.navigation.public.links.stadiums'
    | 'common.navigation.public.title'
    | 'common.theme.dark'
    | 'common.theme.description.dark'
    | 'common.theme.description.light'
    | 'common.theme.description.system'
    | 'common.theme.light'
    | 'common.theme.select'
    | 'common.theme.system'
    | 'common.user.dashboard'
    | 'common.user.email'
    | 'common.user.goToDashboard'
    | 'common.user.logout'
    | 'common.user.menu'
    | 'common.user.name'
    | 'common.user.profile'
    | 'common.user.role'
    | 'common.user.roles.admin'
    | 'common.user.roles.club'
    | 'common.user.signOut'
    | 'common.user.viewProfile'
    | 'common.user.welcome'
    | 'pages.about.metadata.description'
    | 'pages.about.metadata.keywords'
    | 'pages.about.metadata.title'
    | 'pages.contact.metadata.description'
    | 'pages.contact.metadata.keywords'
    | 'pages.contact.metadata.title'
    | 'pages.error.errorId'
    | 'pages.error.goHome'
    | 'pages.error.noStackTrace'
    | 'pages.error.subtitle'
    | 'pages.error.technicalDetails'
    | 'pages.error.title'
    | 'pages.error.tryAgain'
    | 'pages.home.hero.cta'
    | 'pages.home.hero.subtitle'
    | 'pages.home.hero.title'
    | 'pages.home.metadata.description'
    | 'pages.home.metadata.keywords'
    | 'pages.home.metadata.title'
    | 'pages.stadiums.metadata.description'
    | 'pages.stadiums.metadata.keywords'
    | 'pages.stadiums.metadata.title';

  export type TranslationNamespace = keyof typeof _TranslationNamespaces;
}

export const _TranslationNamespaces = {
  "pages": [
    "error.title",
    "error.subtitle",
    "error.tryAgain",
    "error.goHome",
    "error.technicalDetails",
    "error.errorId",
    "error.noStackTrace",
    "home.metadata.title",
    "home.metadata.description",
    "home.metadata.keywords",
    "home.hero.title",
    "home.hero.subtitle",
    "home.hero.cta",
    "stadiums.metadata.title",
    "stadiums.metadata.description",
    "stadiums.metadata.keywords",
    "about.metadata.title",
    "about.metadata.description",
    "about.metadata.keywords",
    "contact.metadata.title",
    "contact.metadata.description",
    "contact.metadata.keywords"
  ],
  "pages.error": [
    "title",
    "subtitle",
    "tryAgain",
    "goHome",
    "technicalDetails",
    "errorId",
    "noStackTrace"
  ],
  "pages.home": [
    "metadata.title",
    "metadata.description",
    "metadata.keywords",
    "hero.title",
    "hero.subtitle",
    "hero.cta"
  ],
  "pages.home.metadata": [
    "title",
    "description",
    "keywords"
  ],
  "pages.home.hero": [
    "title",
    "subtitle",
    "cta"
  ],
  "pages.stadiums": [
    "metadata.title",
    "metadata.description",
    "metadata.keywords"
  ],
  "pages.stadiums.metadata": [
    "title",
    "description",
    "keywords"
  ],
  "pages.about": [
    "metadata.title",
    "metadata.description",
    "metadata.keywords"
  ],
  "pages.about.metadata": [
    "title",
    "description",
    "keywords"
  ],
  "pages.contact": [
    "metadata.title",
    "metadata.description",
    "metadata.keywords"
  ],
  "pages.contact.metadata": [
    "title",
    "description",
    "keywords"
  ],
  "common": [
    "actions.reserve",
    "actions.search",
    "actions.login",
    "actions.register",
    "actions.logout",
    "actions.save",
    "actions.cancel",
    "actions.confirm",
    "actions.delete",
    "actions.edit",
    "actions.view",
    "actions.book",
    "actions.checkout",
    "actions.continue",
    "actions.back",
    "actions.filter",
    "actions.sort",
    "actions.share",
    "actions.download",
    "theme.light",
    "theme.dark",
    "theme.system",
    "theme.select",
    "theme.description.light",
    "theme.description.dark",
    "theme.description.system",
    "user.dashboard",
    "user.profile",
    "user.logout",
    "user.viewProfile",
    "user.goToDashboard",
    "user.signOut",
    "user.menu",
    "user.name",
    "user.email",
    "user.role",
    "user.welcome",
    "user.roles.admin",
    "user.roles.club",
    "modals.logout.title",
    "modals.logout.message",
    "modals.logout.cancel",
    "modals.logout.confirm",
    "navigation.public.title",
    "navigation.public.links.home",
    "navigation.public.links.stadiums",
    "navigation.public.links.about",
    "navigation.public.links.contact",
    "navigation.public.links.sectionTitle"
  ],
  "common.actions": [
    "reserve",
    "search",
    "login",
    "register",
    "logout",
    "save",
    "cancel",
    "confirm",
    "delete",
    "edit",
    "view",
    "book",
    "checkout",
    "continue",
    "back",
    "filter",
    "sort",
    "share",
    "download"
  ],
  "common.theme": [
    "light",
    "dark",
    "system",
    "select",
    "description.light",
    "description.dark",
    "description.system"
  ],
  "common.theme.description": [
    "light",
    "dark",
    "system"
  ],
  "common.user": [
    "dashboard",
    "profile",
    "logout",
    "viewProfile",
    "goToDashboard",
    "signOut",
    "menu",
    "name",
    "email",
    "role",
    "welcome",
    "roles.admin",
    "roles.club"
  ],
  "common.user.roles": [
    "admin",
    "club"
  ],
  "common.modals": [
    "logout.title",
    "logout.message",
    "logout.cancel",
    "logout.confirm"
  ],
  "common.modals.logout": [
    "title",
    "message",
    "cancel",
    "confirm"
  ],
  "common.navigation": [
    "public.title",
    "public.links.home",
    "public.links.stadiums",
    "public.links.about",
    "public.links.contact",
    "public.links.sectionTitle"
  ],
  "common.navigation.public": [
    "title",
    "links.home",
    "links.stadiums",
    "links.about",
    "links.contact",
    "links.sectionTitle"
  ],
  "common.navigation.public.links": [
    "home",
    "stadiums",
    "about",
    "contact",
    "sectionTitle"
  ]
} as const;

export {};
