// ⚠️ AUTO-GENERATED — DO NOT EDIT
// Generated by scripts/generate-i18n.ts

import { useTranslations } from "next-intl";
import { getTranslations } from "next-intl/server";
import { AllTranslationKeys } from "@/types/i18n";

/* ---------------- CLIENT ---------------- */
export function useTypedTranslations(): (key: AllTranslationKeys, values?: Record<string, any>) => string {
  const t = useTranslations();
  return ((key: AllTranslationKeys, values?: Parameters<typeof t>[1]) => t(key, values)) as
    (key: AllTranslationKeys, values?: Parameters<typeof t>[1]) => string;
}

/* ---------------- SERVER ---------------- */
export async function getTypedTranslations(): Promise<(key: AllTranslationKeys, values?: Record<string, any>) => string> {
  const t = await getTranslations();
  return ((key: AllTranslationKeys, values?: Parameters<typeof t>[1]) => t(key, values)) as
    (key: AllTranslationKeys, values?: Parameters<typeof t>[1]) => string;
}
