// ⚠️ AUTO-GENERATED — DO NOT EDIT
// Generated by scripts/generate-i18n.ts

import { useTranslations } from 'next-intl';
import { getTranslations } from 'next-intl/server';
import { _TranslationNamespaces } from '@/types/i18n';

type NamespaceKeys<T extends keyof typeof _TranslationNamespaces> = 
  (typeof _TranslationNamespaces)[T][number];

/**
 * Client-side typed translations
 */
export function useTypedTranslations<T extends keyof typeof _TranslationNamespaces = keyof typeof _TranslationNamespaces>(namespace?: T) {
  const t = useTranslations(namespace as string | undefined);
  return (key: NamespaceKeys<T>, values?: Parameters<typeof t>[1]) =>
    t(key as any, values);
}

/**
 * Server-side typed translations (uses current request locale)
 */
export async function getTypedTranslations<T extends keyof typeof _TranslationNamespaces = keyof typeof _TranslationNamespaces>(namespace?: T) {
  const t = await getTranslations(namespace as string | undefined);
  return (key: NamespaceKeys<T>, values?: Parameters<typeof t>[1]) =>
    t(key as any, values);
}
