import fs from "fs";
import path from "path";

const ROOT = process.cwd();
const MESSAGES_DIR = path.join(ROOT, "messages");
const TYPES_FILE = path.join(ROOT, "types", "i18n.d.ts");
const UTILS_FILE = path.join(ROOT, "utils", "i18n.ts");

/* ---------------- Flatten keys recursively ---------------- */
function flattenKeys(obj: any, prefix = ""): string[] {
  const keys: string[] = [];

  function recurse(o: any, path: string) {
    if (typeof o === "string") {
      keys.push(path);
      return;
    }
    if (typeof o === "object" && o !== null) {
      for (const [k, v] of Object.entries(o)) {
        const newPath = path ? `${path}.${k}` : k;
        recurse(v, newPath);
      }
    }
  }

  recurse(obj, prefix);
  return keys;
}

/* ---------------- Build namespace map with string keys only ---------------- */
function buildStringNamespaceMap(obj: any, prefix = ""): Record<string, string[]> {
  const map: Record<string, string[]> = {};

  function recurse(o: any, path: string) {
    if (typeof o !== "object" || o === null) return;

    // Filter to only include direct children that are strings
    const stringKeys = Object.keys(o).filter(k => k && typeof o[k] === "string");
    if (stringKeys.length) {
      map[path || "root"] = stringKeys;
    }

    // Recurse into each child
    for (const [k, v] of Object.entries(o)) {
      const newPath = path ? `${path}.${k}` : k;
      recurse(v, newPath);
    }
  }

  recurse(obj, prefix);
  return map;
}

/* ---------------- Build full namespace map (all keys) ---------------- */
function buildFullNamespaceMap(obj: any, prefix = ""): Record<string, string[]> {
  const map: Record<string, string[]> = {};

  function recurse(o: any, path: string) {
    if (typeof o !== "object" || o === null) return;

    // Include all direct children
    const directKeys = Object.keys(o).filter(k => k);
    if (directKeys.length) {
      map[path || "root"] = directKeys;
    }

    // Recurse into each child
    for (const [k, v] of Object.entries(o)) {
      const newPath = path ? `${path}.${k}` : k;
      recurse(v, newPath);
    }
  }

  recurse(obj, prefix);
  return map;
}

/* ---------------- Load all JSON files ---------------- */
function loadKeys() {
  const files = fs.readdirSync(MESSAGES_DIR).filter(f => f.endsWith(".json"));
  const allKeys = new Set<string>();
  const stringNamespaceMap: Record<string, string[]> = {};
  const fullNamespaceMap: Record<string, string[]> = {};

  for (const file of files) {
    const json = JSON.parse(fs.readFileSync(path.join(MESSAGES_DIR, file), "utf-8"));
    flattenKeys(json).forEach(k => allKeys.add(k));
    Object.assign(stringNamespaceMap, buildStringNamespaceMap(json));
    Object.assign(fullNamespaceMap, buildFullNamespaceMap(json));
  }

  return {
    keys: Array.from(allKeys).sort(),
    stringNamespaces: stringNamespaceMap,
    fullNamespaces: fullNamespaceMap,
  };
}

const { keys, stringNamespaces, fullNamespaces } = loadKeys();

/* ---------------- Generate TypeScript types ---------------- */
const typesContent = `
// ⚠️ AUTO-GENERATED — DO NOT EDIT
// Generated by scripts/generate-i18n.ts

declare global {
  export type TranslationKey =
${keys.map(k => `    | '${k}'`).join("\n")};

  export type TranslationNamespace = keyof typeof _TranslationNamespaces;
}

export const _TranslationNamespaces = ${JSON.stringify(fullNamespaces, null, 2)} as const;

export const _StringTranslationNamespaces = ${JSON.stringify(stringNamespaces, null, 2)} as const;

export type StringNamespaceKeys<T extends keyof typeof _StringTranslationNamespaces> =
  (typeof _StringTranslationNamespaces)[T][number];

export type NamespaceKeys<T extends keyof typeof _TranslationNamespaces> =
  (typeof _TranslationNamespaces)[T][number];

export type AllTranslationKeys = TranslationKey;

export {};
`;

/* ---------------- Generate client & server utils ---------------- */
const utilsContent = `
// ⚠️ AUTO-GENERATED — DO NOT EDIT
// Generated by scripts/generate-i18n.ts

import { useTranslations } from "next-intl";
import { getTranslations } from "next-intl/server";
import { 
  _StringTranslationNamespaces, 
  StringNamespaceKeys, 
  AllTranslationKeys 
} from "@/types/i18n";

/* ---------------- CLIENT ---------------- */
export function useTypedTranslations<T extends keyof typeof _StringTranslationNamespaces>(
  namespace: T
): (key: StringNamespaceKeys<T>, values?: Parameters<ReturnType<typeof useTranslations>>[1]) => string;

export function useTypedTranslations(): (key: AllTranslationKeys, values?: Parameters<ReturnType<typeof useTranslations>>[1]) => string;

export function useTypedTranslations<T extends keyof typeof _StringTranslationNamespaces>(
  namespace?: T
) {
  const t = useTranslations(namespace as string | undefined);
  return ((key: any, values?: Parameters<typeof t>[1]) => t(key, values)) as
    | ((key: StringNamespaceKeys<T>, values?: Parameters<ReturnType<typeof useTranslations>>[1]) => string)
    | ((key: AllTranslationKeys, values?: Parameters<ReturnType<typeof useTranslations>>[1]) => string);
}

/* ---------------- SERVER ---------------- */
export async function getTypedTranslations<T extends keyof typeof _StringTranslationNamespaces>(
  namespace: T
): Promise<(key: StringNamespaceKeys<T>, values?: Parameters<ReturnType<typeof getTranslations>>[1]) => string>;

export async function getTypedTranslations(): Promise<(key: AllTranslationKeys, values?: Parameters<ReturnType<typeof getTranslations>>[1]) => string>;

export async function getTypedTranslations<T extends keyof typeof _StringTranslationNamespaces>(
  namespace?: T
) {
  const t = await getTranslations(namespace as string | undefined);
  return ((key: any, values?: Parameters<typeof t>[1]) => t(key, values)) as
    | ((key: StringNamespaceKeys<T>, values?: Parameters<ReturnType<typeof getTranslations>>[1]) => string)
    | ((key: AllTranslationKeys, values?: Parameters<ReturnType<typeof getTranslations>>[1]) => string);
}
`;

/* ---------------- Write files ---------------- */
fs.mkdirSync(path.dirname(TYPES_FILE), { recursive: true });
fs.mkdirSync(path.dirname(UTILS_FILE), { recursive: true });

fs.writeFileSync(TYPES_FILE, typesContent.trim() + "\n");
fs.writeFileSync(UTILS_FILE, utilsContent.trim() + "\n");

console.log("✅ i18n types & utils generated with string-only namespace keys");