import fs from 'fs';
import path from 'path';

const ROOT = process.cwd();
const MESSAGES_DIR = path.join(ROOT, 'messages');
const TYPES_FILE = path.join(ROOT, 'types', 'i18n.d.ts');
const UTILS_FILE = path.join(ROOT, 'utils', 'i18n.ts');

interface NamespaceMap {
  [ns: string]: string[];
}

// Recursively flatten all keys
function extractKeys(obj: Record<string, any>, prefix = ''): string[] {
  return Object.entries(obj).flatMap(([key, value]) => {
    const fullKey = prefix ? `${prefix}.${key}` : key;
    if (typeof value === 'string') return [fullKey];
    if (value && typeof value === 'object') return extractKeys(value, fullKey);
    return [];
  });
}

// Build namespace map for all possible namespaces
function extractNamespaces(obj: Record<string, any>, prefix = ''): NamespaceMap {
  const map: NamespaceMap = {};

  const keys: string[] = [];

  for (const [key, value] of Object.entries(obj)) {
    if (typeof value === 'string') {
      keys.push(key);
    } else if (value && typeof value === 'object') {
      keys.push(key);
    }
  }

  if (keys.length > 0 && prefix) {
    // Store relative keys under this namespace
    map[prefix] = extractKeys(obj, ''); 
  }

  // Recurse into children namespaces
  for (const [key, value] of Object.entries(obj)) {
    if (value && typeof value === 'object') {
      const ns = prefix ? `${prefix}.${key}` : key;
      map[ns] = extractKeys(value, ''); // flatten all keys inside child namespace
      Object.assign(map, extractNamespaces(value, ns));
    }
  }

  return map;
}


// Load all keys and namespaces from all JSON files
function loadKeys() {
  const files = fs.readdirSync(MESSAGES_DIR).filter(f => f.endsWith('.json'));
  const allKeys = new Set<string>();
  const namespaceMap: NamespaceMap = {};

  for (const file of files) {
    const json = JSON.parse(fs.readFileSync(path.join(MESSAGES_DIR, file), 'utf-8'));
    extractKeys(json).forEach(k => allKeys.add(k));
    Object.assign(namespaceMap, extractNamespaces(json));
  }

  return {
    keys: Array.from(allKeys).sort(),
    namespaces: namespaceMap,
  };
}

const { keys, namespaces } = loadKeys();

/* ---------------- TYPES ---------------- */

const typesContent = `
// ⚠️ AUTO-GENERATED — DO NOT EDIT
// Generated by scripts/generate-i18n.ts

declare global {
  export type TranslationKey =
${keys.map(k => `    | '${k}'`).join('\n')};

  export type TranslationNamespace = keyof typeof _TranslationNamespaces;
}

export const _TranslationNamespaces = ${JSON.stringify(namespaces, null, 2)} as const;

export {};
`;

/* ---------------- UTILS ---------------- */

const utilsContent = `
// ⚠️ AUTO-GENERATED — DO NOT EDIT
// Generated by scripts/generate-i18n.ts

import { useTranslations } from 'next-intl';
import { getTranslations } from 'next-intl/server';
import { _TranslationNamespaces } from '@/types/i18n';

type NamespaceKeys<T extends keyof typeof _TranslationNamespaces> = 
  (typeof _TranslationNamespaces)[T][number];

/**
 * Client-side typed translations
 */
export function useTypedTranslations<T extends keyof typeof _TranslationNamespaces = keyof typeof _TranslationNamespaces>(namespace?: T) {
  const t = useTranslations(namespace as string | undefined);
  return (key: NamespaceKeys<T>, values?: Parameters<typeof t>[1]) =>
    t(key as any, values);
}

/**
 * Server-side typed translations (uses current request locale)
 */
export async function getTypedTranslations<T extends keyof typeof _TranslationNamespaces = keyof typeof _TranslationNamespaces>(namespace?: T) {
  const t = await getTranslations(namespace as string | undefined);
  return (key: NamespaceKeys<T>, values?: Parameters<typeof t>[1]) =>
    t(key as any, values);
}
`;

/* ---------------- WRITE FILES ---------------- */

fs.mkdirSync(path.dirname(TYPES_FILE), { recursive: true });
fs.mkdirSync(path.dirname(UTILS_FILE), { recursive: true });

fs.writeFileSync(TYPES_FILE, typesContent.trim() + '\n');
fs.writeFileSync(UTILS_FILE, utilsContent.trim() + '\n');

console.log('✅ i18n types & utils (fully nested, namespace-aware, TS-safe) generated');
