import type { Metadata } from "next";
import { Cause, Tajawal } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { LocaleType } from "@/types";
import { getDirection, isRtl } from "@/utils";

const cause = Cause({
  variable: "--font-cause",
  subsets: ["latin", "latin-ext"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Specify weights you need
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: LocaleType }>;
}>) {
  const { locale } = await params;
  const messages = (await import(`../../../messages/${locale}.json`)).default;
  return (
    <html lang={locale} dir={getDirection(locale)}>
      <body className={`${cause.variable}  antialiased font-medium`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
